language: node_js
node_js: 11
cache: yarn
jobs:
  include:
    - stage: test
      after_success: yarn coverage
    - stage: deploy
      script: yarn build
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        email: $NPM_email
        skip_cleanup: true
        on:
          branch: master
      before_deploy: sed -i 's/dist//g' .gitignore
