language: node_js
node_js: 11
cache: yarn
jobs:
  include:
    - stage: test
      after_success: yarn coverage
    - stage: deploy
      script: yarn build
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
        on:
          branch: master
      before_deploy: sed -i 's/dist//g' .gitignore
